// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://lypjkrlbmpptiayubgym.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx5cGprcmxibXBwdGlheXViZ3ltIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjUyOTQyODUsImV4cCI6MjA4MDg3MDI4NX0.udKW2RrHK9pDILyyLwjhwhqA9c9G8HGL4QyS981BMRQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);